name: msunet
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.0=py311h06a4308_0
  - python=3.11.11=he870216_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py311h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - acvl-utils==0.2.5
      - argparse==1.4.0
      - asttokens==3.0.0
      - batchgenerators==0.25.1
      - blosc2==3.3.1
      - causal-conv1d==1.5.0.post8
      - certifi==2025.1.31
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - cloudpickle==3.1.1
      - connected-components-3d==3.23.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - decorator==5.2.1
      - dicom2nifti==2.6.0
      - dynamic-network-architectures==0.3.1
      - einops==0.8.1
      - executing==2.2.0
      - filelock==3.18.0
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - graphviz==0.20.3
      - huggingface-hub==0.30.2
      - idna==3.10
      - imagecodecs==2025.3.30
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - iopath==0.1.10
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - linecache2==1.0.0
      - mamba-ssm==2.2.4
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - medpy==0.5.2
      - monai==1.3.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - ndindex==1.9.2
      - networkx==3.4.2
      - nibabel==5.3.2
      - ninja==1.11.1.4
      - numexpr==2.10.2
      - numpy==2.2.5
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - onnx==1.17.0
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.7
      - pluggy==1.5.0
      - portalocker==3.1.1
      - prompt-toolkit==3.0.51
      - protobuf==6.30.2
      - ptflops==0.7.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pydicom==3.0.1
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - python-gdcm==3.0.24.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - selective-scan==0.0.2
      - simpleitk==2.4.1
      - six==1.17.0
      - stack-data==0.6.3
      - submitit==1.5.2
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboardx==2.6.2.2
      - termcolor==3.0.1
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - tifffile==2025.3.30
      - timm==0.4.12
      - tokenizers==0.21.1
      - torch==2.6.0
      - torch-print-summary==1.0.2
      - torchaudio==2.6.0
      - torchinfo==1.8.0
      - torchview==0.2.7
      - torchvision==0.21.0
      - tqdm==4.67.1
      - traceback2==1.4.0
      - traitlets==5.14.3
      - transformers==4.51.3
      - triton==3.2.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - unittest2==1.1.0
      - urllib3==2.4.0
      - wcwidth==0.2.13
      - yacs==0.1.8
prefix: /home/msp/miniconda3/envs/mamba
